// Code generated by protoc-gen-go. DO NOT EDIT.
// source: view.proto

package viewproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpRequest struct {
	Method               string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Query                string            `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HttpRequest) Reset()         { *m = HttpRequest{} }
func (m *HttpRequest) String() string { return proto.CompactTextString(m) }
func (*HttpRequest) ProtoMessage()    {}
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c1b2aca93c333f, []int{0}
}

func (m *HttpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequest.Unmarshal(m, b)
}
func (m *HttpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequest.Marshal(b, m, deterministic)
}
func (m *HttpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequest.Merge(m, src)
}
func (m *HttpRequest) XXX_Size() int {
	return xxx_messageInfo_HttpRequest.Size(m)
}
func (m *HttpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequest proto.InternalMessageInfo

func (m *HttpRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HttpRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *HttpRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type HttpResponse struct {
	Status               int32             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HttpResponse) Reset()         { *m = HttpResponse{} }
func (m *HttpResponse) String() string { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()    {}
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10c1b2aca93c333f, []int{1}
}

func (m *HttpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpResponse.Unmarshal(m, b)
}
func (m *HttpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpResponse.Marshal(b, m, deterministic)
}
func (m *HttpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpResponse.Merge(m, src)
}
func (m *HttpResponse) XXX_Size() int {
	return xxx_messageInfo_HttpResponse.Size(m)
}
func (m *HttpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HttpResponse proto.InternalMessageInfo

func (m *HttpResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *HttpResponse) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpRequest)(nil), "gapi.handler.httpview.HttpRequest")
	proto.RegisterMapType((map[string]string)(nil), "gapi.handler.httpview.HttpRequest.HeadersEntry")
	proto.RegisterType((*HttpResponse)(nil), "gapi.handler.httpview.HttpResponse")
	proto.RegisterMapType((map[string]string)(nil), "gapi.handler.httpview.HttpResponse.HeadersEntry")
}

func init() { proto.RegisterFile("view.proto", fileDescriptor_10c1b2aca93c333f) }

var fileDescriptor_10c1b2aca93c333f = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xcb, 0x4c, 0x2d,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4d, 0x4f, 0x2c, 0xc8, 0xd4, 0xcb, 0x48, 0xcc,
	0x4b, 0xc9, 0x49, 0x2d, 0xd2, 0xcb, 0x28, 0x29, 0x29, 0x00, 0x49, 0x2a, 0x5d, 0x63, 0xe4, 0xe2,
	0xf6, 0x28, 0x29, 0x29, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0xcb,
	0x4d, 0x2d, 0xc9, 0xc8, 0x4f, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x44,
	0xb8, 0x58, 0x0b, 0x4b, 0x53, 0x8b, 0x2a, 0x25, 0x98, 0xc0, 0xc2, 0x10, 0x8e, 0x90, 0x27, 0x17,
	0x7b, 0x46, 0x6a, 0x62, 0x4a, 0x6a, 0x51, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xbe,
	0x1e, 0x56, 0x6b, 0xf4, 0x90, 0xac, 0xd0, 0xf3, 0x80, 0xe8, 0x70, 0xcd, 0x2b, 0x29, 0xaa, 0x0c,
	0x82, 0xe9, 0x17, 0x12, 0xe2, 0x62, 0x49, 0xca, 0x4f, 0xa9, 0x94, 0x60, 0x51, 0x60, 0xd4, 0xe0,
	0x09, 0x02, 0xb3, 0xa5, 0xac, 0xb8, 0x78, 0x90, 0x15, 0x0b, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56,
	0x42, 0x5d, 0x06, 0x62, 0x82, 0x9c, 0x55, 0x96, 0x98, 0x53, 0x9a, 0x0a, 0x73, 0x16, 0x98, 0x63,
	0xc5, 0x64, 0xc1, 0xa8, 0x74, 0x88, 0x91, 0x8b, 0x07, 0x62, 0x6b, 0x71, 0x41, 0x7e, 0x5e, 0x71,
	0x2a, 0xc8, 0x67, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x60, 0xfd, 0xac, 0x41, 0x50, 0x9e, 0x90,
	0x17, 0xc2, 0x0f, 0x4c, 0x60, 0x3f, 0x18, 0xe0, 0xf5, 0x03, 0xc4, 0x34, 0x02, 0x9e, 0x60, 0xa6,
	0x8e, 0x27, 0x9c, 0xb8, 0xa3, 0x38, 0x41, 0x56, 0x83, 0x63, 0x30, 0x89, 0x0d, 0x4c, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x1d, 0xac, 0x04, 0xd6, 0x01, 0x00, 0x00,
}
